# Generated by Django 3.1.4 on 2020-12-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_testimagefield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestImageField',
        ),
    ]
